# docker-compose.yaml
services:
  db:
    image: postgres:13-alpine
    container_name: audio-saas-db
    restart: 'no'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    container_name: audio-saas-redis
    restart: 'no'
    ports:
      - '6379:6379'

  engagement-redis:
    image: redis:7-alpine
    container_name: audio-saas-engagement-redis
    restart: 'no'
    ports:
      - '6380:6379'

  rate-limit-redis:
    image: redis:7-alpine
    container_name: audio-saas-ratelimit-redis
    restart: 'no'
    ports:
      - '6381:6379'

  caching-redis:
    image: redis:7-alpine
    container_name: audio-saas-caching-redis
    restart: 'no'
    ports:
      - '6382:6379'

  engagement-bg-svc:
    container_name: engagement-bg-svc
    image: audiosass-engagement-bg-svc
    build: ./packages/engagement-bg-svc
    restart: 'no'
    network_mode: host
    env_file:
      - ./packages/engagement-bg-svc/.env

  datadog-agent:
    image: registry.datadoghq.com/agent:7
    container_name: dd-agent
    restart: 'no'
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE:-datadoghq.com}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_TRACE_ENABLED=true
    ports:
      - '8126:8126' # APM Traces (Node dd-trace hits this port)
      - '8125:8125/udp' # DogStatsD (Metrics)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
